dashboard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from reports import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
	# url(r'^$', views.home, name='home'),
 #    url(r'^admin/', admin.site.urls),
 #    url(r'^execute/', views.execute, name='execute'),
 #    url(r'^projects/$', views.projects, name='projects'),
 #    url(r'^(?P<pk>\d+)/about/', views.about, name='about'),
 #    url(r'^status/$', views.status, name='status'),
 #    url(r'^projects/(?P<pk>\d+)/testplans/$', views.project_testplans, name='project_testplans'),
 #    url(r'^projects/(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/$', views.testplan_testcycles, name='testplan_testcycles'),
	# url(r'^projects/(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/newtestcycle/$', views.new_testcycle, name='new_testcycle'),
	# url(r'^projects/(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/(?P<testcycle_pk>\d+)/report/$', views.report, name='report')

	url(r'^$', views.home, name='home'),
	url(r'^admin/', admin.site.urls),
    url(r'^jenkins_projects/', include('executetests.urls')),
    url(r'^projects/', include('reports.urls')),
    url(r'^status/$', views.status, name='status'),
]

reports/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

	url(r'^$', views.projects, name='projects'),
    url(r'^(?P<pk>\d+)/about/', views.about, name='about'),
    url(r'^(?P<pk>\d+)/testplans/$', views.project_testplans, name='project_testplans'),
    #url(r'^projects/(?P<pk>\d+)/newtestplan/$', views.new_testplan, name='new_testplan'),
    url(r'^(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/$', views.testplan_testcycles, name='testplan_testcycles'),
	url(r'^(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/newtestcycle/$', views.new_testcycle, name='new_testcycle'),
	url(r'^(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/(?P<testcycle_pk>\d+)/report/$', views.report, name='report'),
	url(r'^(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/(?P<testcycle_pk>\d+)/detailed_report/$', views.detailed_report, name='detailed_report'),
    url(r'^(?P<pk>\d+)/testplans/(?P<testplan_pk>\d+)/testcycles/(?P<testcycle_pk>\d+)/issue/$', views.create_jira_issue, name='create_jira_issue'),
]

reports/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.contrib.auth.models import User
from django.conf import settings


class Project(models.Model):
	name=models.CharField(max_length=30, unique=True)
	description=models.TextField(max_length=2000, help_text='Max characters limit is 2000')
	jira_key = models.CharField(max_length=15, unique=True)
	scripting_language=models.CharField(max_length=50)
	tools=models.CharField(max_length=50)
	total_testcases_in_project = models.PositiveSmallIntegerField()
	total_automatable_testcases = models.PositiveSmallIntegerField()
	automated_testcases = models.PositiveSmallIntegerField()

	def __str__(self):
		return self.name


class TestPlan(models.Model):
	name=models.CharField(max_length=50)
	description=models.TextField(max_length=500, help_text='Enter a brief description about this release. For Example: You can enter the details about "New Features added" etc.')
	project=models.ForeignKey(Project, related_name='testplans')
	created_at=models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.name


class TestCycle(models.Model):
	name=models.CharField(max_length=20)
	testplan=models.ForeignKey(TestPlan, related_name='testcycles')

	def __str__(self):
		return self.name


class Result(models.Model):
	updated_at=models.DateTimeField(auto_now_add=True)
	last_executed = models.CharField(max_length=40)
	testcycle=models.ForeignKey(TestCycle, related_name='results')
	total_testcases=models.PositiveSmallIntegerField()
	pass_count=models.PositiveSmallIntegerField()
	fail_count=models.PositiveSmallIntegerField()
	norun_count=models.PositiveSmallIntegerField()
	duration=models.CharField(max_length=8, default="None")
	detailed_report=models.TextField(max_length=200)
	jira_issue_ids = models.TextField(null=True)

class TestCyclesList(models.Model):
	name=models.CharField(max_length=30, unique=True)

reports/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from .models import Project, TestPlan, TestCycle, Result, TestCyclesList
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from jira import JIRA

import os
import shutil
import datetime
import xmltodict
import json

# Create your views here.

TEST_CYCLES = [
	'Smoke',
	'Sanity', 
	'Functional', 
	'Performance', 
	'Memory', 
	'Stress', 
	'Load', 
	'Compatibility', 
	'NonFunctional'
]


JIRA_CREDENTIALS = {
	
	'username' : 'HProTestAutomation',
	'password' : 'Dashboard@123'
}


def home(request):
	projects = Project.objects.all()
	return render(request, 'home.html', {'projects' : projects})


def execute(request):
	projects = Project.objects.all()
	return render(request, 'run_automated_tests.html', {'projects' : projects})


def status(request):
	projects = Project.objects.all()
	projects_count = len(projects)

	return render(request, 'status.html', {'projects' : projects, 'projects_count' : projects_count})


def about(request, pk):
	project = Project.objects.get(pk=pk)
	return render(request, 'about.html', {'project' : project})


def projects(request):
	projects = Project.objects.all()
	#admin = User.objects.get(username='trastogi')
	_create_project_dirs(projects)
	return render(request, 'projects.html', {'projects' : projects})


def project_testplans(request, pk):
	project = Project.objects.get(pk=pk)
	testplans = project.testplans.all().order_by('-created_at')
	_create_testplan_dirs(project, testplans)
	return render(request, 'project_testplans.html', {'project' : project, 'testplans' : testplans})


def testplan_testcycles(request, pk, testplan_pk):
	testplan = get_object_or_404(TestPlan, project__pk=pk, pk=testplan_pk)
	testcycles = testplan.testcycles.all()

	_create_testcycles_dirs(testplan, testcycles)

	testcycle_attributes = []
	for testcycle in testcycles:
		latest_report = _get_latest_report(testcycle.pk)

		if not latest_report:
			testcycle_attributes.append([testcycle, testcycle.name, ""])
		else:
			testcycle_attributes.append([testcycle, testcycle.name, latest_report.last_executed])

	return render(request, 'testplan_testcycles.html', {'testplan' : testplan, 'testcycle_attributes' : testcycle_attributes})


def new_testcycle(request, pk, testplan_pk):
	testplan = get_object_or_404(TestPlan, project__pk=pk, pk=testplan_pk)
	added_testcycles = [testcycle.name for testcycle in testplan.testcycles.all()]
	_add_remove_testcycles_to_db()

	testcycleslist = TestCyclesList.objects.all()

	if request.method == 'POST':
		sel_testcycles = request.POST.getlist('mymultiselect')

		for i in range(len(sel_testcycles)):
			sel_testcycle = TestCyclesList.objects.get(id=sel_testcycles[i])
			sel_testcycle_name = sel_testcycle.name

			if sel_testcycle_name not in added_testcycles:
				testcycle = TestCycle.objects.create(
					name=sel_testcycle_name, 
					testplan=testplan, 
				)
		return redirect('testplan_testcycles', pk=pk, testplan_pk=testplan_pk)

	return render(request, 'new_testcycle.html', {'testplan' : testplan, 'added_testcycles' : added_testcycles, 'testcycleslist' : testcycleslist})


def report(request, pk, testplan_pk, testcycle_pk):
	testcycle = get_object_or_404(TestCycle, testplan__pk=testplan_pk, pk=testcycle_pk)
	project = Project.objects.get(pk=pk)

	_fetch_valid_reports_and_update(project, testcycle)

	msg = None
	requested_builds = 5
	reports_list=[]
	reports_list_count = 0
	compared_testplan = None
	available_testplans_list_for_comp = []


	# if request.method == 'POST' and request.FILES['myfile']:
	# 	myfile = request.FILES['myfile']
	# 	report_dir = _handle_uploaded_file(request.FILES['myfile'])

	# 	msg = _enter_report_data_in_db(testcycle.id, report_dir)


	if request.method == 'GET' and '5 builds' in request.GET:
		requested_builds = 5
	elif request.method == 'GET' and '10 builds' in request.GET:
		requested_builds = 10
	elif request.method == 'GET' and '20 builds' in request.GET:
		requested_builds = 20


	for tp in project.testplans.all():
		if tp.pk != testcycle.testplan.pk:
			try:
				tc = tp.testcycles.get(name=testcycle.name)
			except:
				continue

			if not _get_latest_report(tc.pk):
				continue

			available_testplans_list_for_comp.append(tp)


	if request.method == 'GET' and 'comparereleases' in request.GET:
		compared_testplans_id = request.GET.getlist('previous_releases_list')

		for compared_testplan_id in compared_testplans_id:
			compared_testplan = TestPlan.objects.get(pk=compared_testplan_id)
		 	compared_testcycle = compared_testplan.testcycles.get(name=testcycle.name)
			reports_list.append(_get_latest_report(compared_testcycle.pk))

		reports_list.append(_get_latest_report(testcycle.pk))
		reports_list_count = len(reports_list)


	latest_report = _get_latest_report(testcycle.pk)
	all_reports_count = _get_all_reports_count(testcycle.pk)

	all_req_reports = _get_all_req_reports_for_this_testcycle(testcycle.pk, requested_builds)
	all_req_reports_count = len(all_req_reports)

	return render(request, 'report.html', 
		{'testcycle' : testcycle, 'project' : project, 'latest_report' : latest_report, 'all_reports_count' : all_reports_count, 'all_req_reports' : all_req_reports, 'all_req_reports_count' : all_req_reports_count, 'requested_builds' : requested_builds, 'msg' : msg, 'reports_list' : reports_list, 'reports_list_count' : reports_list_count, 'compared_testplan' : compared_testplan, 'available_testplans_list_for_comp' : available_testplans_list_for_comp}
	)


def detailed_report(request, pk, testplan_pk, testcycle_pk):

	PRIORITY_LIST = [
		'Blocker',
		'Critical',
		'Major',
		'Minor',
		'Trivial'
	]

	jira_issues_list = None

	testcycle = get_object_or_404(TestCycle, testplan__pk=testplan_pk, pk=testcycle_pk)
	project = Project.objects.get(pk=pk)
	latest_report = _get_latest_report(testcycle.pk)
	jira_issues = latest_report.jira_issue_ids
	if jira_issues:
		jira_issues_list = str(jira_issues).split("/")

	jira_project_name = None
	available_affected_versions_list = None
	available_components_list = None
	priority_list = PRIORITY_LIST


	jira = _login_to_jira(JIRA_CREDENTIALS['username'], JIRA_CREDENTIALS['password'])

	try:
		jira_project = jira.project(str(project.jira_key))
	except:
		jira_project = None

	if jira_project:
		jira_project_name = jira_project.name
		available_affected_versions_list = [str(version.name) for version in jira_project.versions]
		available_components_list = [str(component.name) for component in jira_project.components]


	return render(request, 'detailed_report.html', {'jira' : jira, 'testcycle' : testcycle, 'latest_report' : latest_report, 'jira_project_name' : jira_project_name, 'priority_list' : priority_list, 'available_affected_versions_list' :available_affected_versions_list, 'available_components_list' : available_components_list, 'jira_issues_list' : jira_issues_list})


def create_jira_issue(request, pk, testplan_pk, testcycle_pk):

	project = Project.objects.get(pk=pk)

	jira = _login_to_jira(JIRA_CREDENTIALS['username'], JIRA_CREDENTIALS['password'])

	if request.method == 'POST':
		summary = request.POST['summary']
		priority = request.POST['priority']
		description = request.POST['description']
		selected_affected_versions_list = request.POST.getlist('affected_versions')
		affected_versions = [{'name' : str(version)} for version in selected_affected_versions_list]
		selected_components_list = request.POST.getlist('components')
		selected_components = [{'name' : str(component) for component in selected_components_list}]

		jira_issue = jira.create_issue(project=str(project.jira_key), summary=summary, description=description, issuetype='Bug', priority={'name' : priority}, versions=affected_versions, components=selected_components)

		jira_id=str(jira_issue.key)
		latest_report = _get_latest_report(testcycle_pk)

		if not latest_report.jira_issue_ids:
			latest_report.jira_issue_ids = jira_id
		else:
			latest_report.jira_issue_ids = latest_report.jira_issue_ids + "/" + jira_id

		latest_report.save()

		#return HttpResponse(json.dumps({'jira_id': jira_id}))

		return redirect('detailed_report', pk=pk, testplan_pk=testplan_pk, testcycle_pk=testcycle_pk)


def _login_to_jira(username, password):
	global jira_login

	try:
		if jira_login:
			pass
	except:
		jira_login=JIRA("https://jira.harman.com/jira", basic_auth=(username, password))

	return jira_login


def _add_remove_testcycles_to_db():
	testcycleslist = TestCyclesList.objects.all()
	available_testcycles_names = [available_testcycle.name for available_testcycle in testcycleslist]
	for i in range(len(TEST_CYCLES)):
		if TEST_CYCLES[i] not in available_testcycles_names:
			TestCyclesList.objects.create(name=TEST_CYCLES[i])

	for i in range(len(available_testcycles_names)):
		if available_testcycles_names[i] not in TEST_CYCLES:
			tc_to_be_deleted = TestCyclesList.objects.get(name=available_testcycles_names[i])
			tc_to_be_deleted.delete()


def _get_latest_report(testcycle_id):

	latest_report=Result.objects.filter(testcycle_id=testcycle_id).order_by('-last_executed')

	if not latest_report:
		latest_report=None
	else:
		latest_report = latest_report[0]

	return latest_report


def _get_all_reports_count(testcycle_id):

	reports=Result.objects.filter(testcycle_id=testcycle_id)
	return len(reports)


def _get_all_req_reports_for_this_testcycle(testcycle_id, requested_builds):
	
	all_reports=Result.objects.filter(testcycle_id=testcycle_id).order_by('-last_executed')
	req_reports = all_reports[:requested_builds][::-1]

	return req_reports


def _handle_uploaded_file(myfile):

	## Validate if the uploaded file is xml file
	uploaded_xml = myfile

	report_dir = os.path.join(settings.XML_ROOT, datetime.datetime.now().strftime('%Y-%m-%dT%H-%M-%S'))

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Test Automation Dashboard{% endblock %}</title>
		<link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet"> 
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/app.css' %}">
		{% block stylesheet %}{% endblock %}
		
		{% block scripts %}
		{% endblock %}

	</head>
	<body>
		{% block body %}
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<div class="container">
					<a class="navbar-brand" href="{% url 'home' %}">Test Automation Dashboard</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="mainMenu">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								<a class="nav-link" href="#" style="color:lightgrey; position:right;">Welcome {{ user.first_name }}</a>
							</li>
						</ul>
					</div>
					<div class="mb-1">
						<a href="/admin/" class="btn btn-primary">Configure</a>
					</div>
				</div>
			</nav>
			
			<div class="container">
				<ol class="breadcrumb my-3">
					{% block breadcrumb %}
					{% endblock %}
				</ol>
				{% block content %}
				{% endblock %}
			</div>
		{% endblock body %}
	</body>
</html>

templates/console_output.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

	{% block title %}Console Output{% endblock %}
	
	{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
		<li class="breadcrumb-item"><a href="{% url 'jenkins_projects' %}">Projects</a></li>
		<li class="breadcrumb-item"><a href="{% url 'project_jobs' server.pk view_name %}">{{view_name}}</a></li>
		<li class="breadcrumb-item"><a href="{% url 'job_config' server.pk view_name job_name %}">{{job_name}}</a></li>
		<li class="breadcrumb-item">#{{build_number}}</li>
	{% endblock %}
	
	
	{% block scripts %}
	{% endblock %}
	

	{% block content %}
		<br>
		<p> <a href="{% url 'job_config' server.pk view_name job_name %}"><- Back to build listings</a></p>
		<h3>Console Output</h3>		
		<hr>
		<br>
		<pre>{{output}}<pre>
	{% endblock %}

templates/detailed_report.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<title>Detailed Report</title> 
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/app.css' %}">
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	</head>
	
	<body>
		<br>
		<div>
			<table style="width:100%">
				<tbody>
					<td style="width:19%; color:red">&emsp;&emsp;<b>Issues raised in this build iteration:</b>
					{% if not jira_issues_list %}
						<td style="width:71%">None</td>
					{% else %}
						<td style="width:71%">{% for issue_id in jira_issues_list %} <a href="https://jira.harman.com/jira/browse/{{issue_id}}">{{issue_id}}</a>, {% endfor %}</td>
					{% endif %}
					<td style="width:10%">
						<button type="submit" class="btn btn-warning" style="width:140px;font-size:15px;" data-toggle="modal" data-target="#myModal" name="jira_form" id="jira_form" onClick="myFunction()">Create JIRA issue</button>
					</td>
				</tbody>
			</table>
		</div>
	
		<div class="container" >
			<div class="modal fade" id="myModal" role="dialog">
				<div class="modal-dialog modal-lg">
			
					<div class="modal-content">
						<div class="modal-header">
							<p class="modal-title" style="font-size:19px">Create JIRA Issue</p>
							
							<button type="button" class="close" data-dismiss="modal">&times;</button>
							</form>
						</div>
						<form id="jira_issue_form" action="{% url 'create_jira_issue' testcycle.testplan.project.pk testcycle.testplan.pk testcycle.pk %}" method="post">
							{% csrf_token %}
							<div class="modal-body">
								<br>
								<table style="width:100%">
									<tbody>
										<td style="width:60%"><b>Project :</b>&ensp;{{jira_project_name}}</td>
										<td style="width:40%"><b>Issuetype :</b>&ensp;<img src="{% static 'img/bug.png' %}" style="padding: 1px"/>Bug</td>
									</tbody>
								</table>
								<br><br>
								<table style="width:100%">
									<tbody>							
										<tr>
											<td style="width:16%">Summary <img src="{% static 'img/asterisk.png' %}"/></td>
											<td style="width:84%"><input style="width: 95%;font-size:14px;border:1px solid; border-color:#ccc;padding: 6px;box-shadow: inset 0 1px 1px;border-radius: 3px;" type="text" id="id_summary" name="summary" required/></td>
										</tr>
										<tr>
											<td><br></td>
											<td><br></td>
										</tr>
										<tr>
											<td style="width:16%">Priority </td>
											<td style="width:84%">
												<select name="priority" style="width: 95%;font-size:14px;border:1px solid; border-color:#ccc;padding: 6px;box-shadow: inset 0 1px 1px;border-radius: 3px;">
													{% for priority in priority_list %}
														<option value="{{priority}}" {% if priority == "Major" %} selected {% endif %}>{{ priority }}</option>
													{% endfor %}
												</select>
											</td>										
										</tr>
										<tr>
											<td><br></td>
											<td><br></td>
										</tr>
										<tr>
											<td style="width:16%">Affects Version/s </td>
											<td style="width:84%">
												<select name="affected_versions" style="width: 95%;font-size:14px;border:1px solid; border-color:#ccc;padding: 6px;box-shadow: inset 0 1px 1px;border-radius: 3px;">
													{% for version in available_affected_versions_list %}
														<option value="{{version}}" selected>{{ version }}</option>
													{% endfor %}
												</select>
											</td>										
										</tr>
										<tr>
											<td><br></td>
											<td><br></td>
										</tr>
										<tr>
											<td style="width:15%">Component/s </td>
											<td style="width:85%">
												<select name="components" style="width: 95%;font-size:14px;border:1px solid; border-color:#ccc;padding: 6px;box-shadow: inset 0 1px 1px;border-radius: 3px;" required>
													<option disabled selected value>-- Select an option --</option>
													{% for component in available_components_list %}
														<option value="{{component}}">{{ component }}</option>
													{% endfor %}
												</select>
											</td>										
										</tr>
										<tr>
											<td><br></td>
											<td><br></td>
										</tr>									
										<tr>
											<td style="width:15%">Description </td>
											<td style="width:85%">
											<textarea rows="8" style="width: 95%;font-size:14px;border:1px solid; border-color:#ccc;padding: 6px;box-shadow: inset 0 1px 1px;border-radius: 3px;" type="text" id="id_description" name="description">PreCondition:&#10;&#10;Steps:&#10;&#10;&#10;Expected Output:&#10;&#10;Actual Behavior:&#10;&#10;</textarea>
											</td>
										</tr>
										<tr>
											<td><br></td>
											<td><br></td>
										</tr>
									</tbody>
								</table>
							</div>
						
							<div class="modal-footer">
								{% if jira_project_name %}
									<button type="submit" class="btn btn-primary mr-auto" name="create_issue" id="create_issue" style="font-size:17px;">Create</button>
								{% else %}
									<button type="submit" class="btn btn-secondary mr-auto" disabled name="create_issue" id="create_issue" style="font-size:17px;">Create</button>
								{% endif %}
								<button type="button" class="btn btn-default" data-dismiss="modal" style="font-size:17px;">Close</button>
								
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>

		<br>
		<iframe id="report_iframe" src="{% static latest_report.detailed_report %}" seamless style="position:fixed; top:60px; bottom:0px; right:15px; width: 98%; border: none; margin:0; padding:0; overflow: auto; height: 91%;"></iframe>
	</body>

	<script>
		$('#myModal').on('hidden.bs.modal', function () {
			$(this).find('form').trigger('reset');
		});
	</script>
</html>
	

templates/home.html
{% extends 'base.html' %}
{% load static %}
	{% block breadcrumb %}
		<li class="breadcrumb-item">Home</li>
	{% endblock %}
	
	{% block content %}
		<div align="center">
			<br>
			<h3>Welcome to the Test Automation Dashboard!</h3>
			<br><br>
			<p style="font-size:110%;"> What would you like to do today?</p>
			<div class="mb-4">
				<a href="{% url 'jenkins_projects' %}" class="btn btn-primary" id="1">Run Automated Tests</a>&ensp;<a href="{% url 'projects' %}" class="btn btn-primary" id="2">View Reports</a>&ensp;<a href="{% url 'status' %}" class="btn btn-primary" id="3">View Automation Status</a>
			</div><br>
			<hr size="100">
		</div>
		<div align="center">
			<h3  style="color:#d55413;"><strong><u>Our Projects Portfolio</u></strong></h3><br>
			<div>
				<img src="{% static 'img/STUDER.png' %}"/>&emsp;&emsp;&emsp;&emsp;<img src="{% static 'img/MARTIN.png' %}"/>&emsp;&emsp;&emsp;&emsp;<img src="{% static 'img/PM.png' %}"/>&emsp;&emsp;&emsp;&emsp;<img src="{% static 'img/AMX.png' %}"/><br>
				<img src="{% static 'img/DIOS.png' %}"/>&emsp;&emsp;&emsp;&emsp;<img src="{% static 'img/AA.png' %}"/>&emsp;&emsp;&emsp;&emsp;<img src="{% static 'img/JBL.png' %}"/>
			</div>
		</div>
	{% endblock %}

templates/new_testcycle.html
{% extends 'base.html' %}
	{% block title %}Add a New Test Cycle{% endblock %}
	
	{% block breadcrumb %}
		<li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
		<li class="breadcrumb-item"><a href="{% url 'projects' %}">Projects</a></li>
		<li class="breadcrumb-item"><a href="{% url 'project_testplans' testplan.project.pk %}">{{ testplan.project.name }}</a></li>
		<li class="breadcrumb-item"><a href="{% url 'testplan_testcycles' testplan.project.pk testplan.pk %}">{{ testplan.name }}</a></li>
		<li class="breadcrumb-item">Add Test Cycle</li>
	{% endblock %}
	
	{% block content %}
		<br>
		<p style="background-color:black; color:white;"><b>&ensp;Select Test Cycle(s) to add:</b></p>
		<form method="post">
			{% csrf_token %}
			<div class="form-group">
				{% for available_testcycle in testcycleslist %}
					{% if available_testcycle.name not in added_testcycles %}
						<input type="checkbox" id="mymultiselect" option value="{{available_testcycle.pk}}" name="mymultiselect">&ensp;{{available_testcycle.name}}</input><br>
					{% endif %}
				{% endfor %}
			</div>
			<button type="submit" class="btn btn-success">Add</button>
		</form>
		<br><br>
		<p><u>NOTE</u> :&emsp;Contact the admin if the test cycle you want to add is not present in the above list.<p>
	{% endblock %}
	